# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UrbanSARCA
                                 A QGIS plugin
 Plugin for analysis of radioactive contamination ov vegetation cover in urban environment 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-03-31
        copyright            : (C) 2020 by Jakub Brom, ENKI o.p.s. Třeboň
        email                : jbrom@lanres.cz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UrbanSARCA class from file UrbanSARCA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .urban_sarca import UrbanSARCA
    return UrbanSARCA(iface)
